name: build artifacts

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - uses: pre-commit/action@v3.0.0

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      
    - name: build samples
      run: |
        ./gradlew :native-activity:app:task
    - uses: actions/upload-artifact@v4
      with:
        name: NdkSample-build-${{ steps.slug.outputs.sha8 }}
        path: |
               /home/runner/work/ndk-samples/ndk-samples/native-activity/app/build/outputs/
